"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Weight_1 = require("./Weight");
const Answer_1 = require("./Answer");
const Exam_1 = require("./Exam");
const pesos = new Weight_1.Weight([2, 2, 2, 2, 2]);
const gabarito = new Answer_1.Answer("Gabarito", ['a', 'b', 'a', 'c', 'd']);
const prova = new Exam_1.Exam(gabarito, pesos);
const aluno1Teste = new Answer_1.Answer("Aluno 1", ['a', 'b', 'b', 'b', 'b']);
const aluno2Teste = new Answer_1.Answer("Aluno 2", ['a', 'b', 'a', 'c', 'd']);
const aluno3Teste = new Answer_1.Answer("Aluno 2", ['a', 'b', 'c', 'c', 'd']);
prova.add(aluno1Teste);
prova.add(aluno2Teste);
prova.add(aluno3Teste);
console.log("Média:", prova.avg());
console.log("Notas menores que 6:", prova.lt(6));
console.log("Notas maiores que 6:", prova.gt(6));
console.log("Menor nota:", prova.min());
console.log("Maior nota:", prova.max());
